### ISSUE TITLE
Saving output of filtration and reuploading to compute cohomology

### ISSUE THREAD

**Issue by fbarfi** [mrzv/dionysus#56] opened 2022-10-27 15:31 UTC
I have been able to save the outputs of filtration and diagrams into xarray.Dataset.  This is very nice as it allows one to preserve all the data in the outputs in a transparent way. 
I now face the challenge of how to reconvert these saved data into forms that are recognizable to Dionysus 2. I want to save into the disk so that I do not have to recalculate everything every time (it takes many hours on a fast M1 max Mac). Any suggestions?

**Comment by mrzv** [comment] 2022-10-27 17:12
I'm afraid I don't know what `xarray.Dataset` is, nor do I fully understand what you are trying to save. A code example would help.

Also, since this is not a bug report — at least not as far as I can tell — it probably belongs on the mailing list. Please send it there. Meanwhile I'll close this issue.

**Closed by mrzv** 2022-10-27 17:12 UTC
